### PR TITLE
Call CSS property updater on computed property change

### PR DESCRIPTION
**Pull request by Ajnasz**
Issue:
A computed property change not necessarily will call the willRender
function therefore the custom css properties will not update.

Add observers which calls the custom css property updater when the
computed property changes.

### CODE REVIEW

**Comment by hilljh82** [comment]
@Ajnasz Thanks for your pull request. Before accepting it, do you a simple example that illustrates the problem your pull request is resolving?

**Comment by Ajnasz** [comment]
@hilljh82 Here is one https://github.com/Ajnasz/emberjs-custom-properties-example-for-fix

Changing a property in `example2` which would be used in `example.js` to generate a custom property.
The `example` component will not be rerendered because it's content will not change, so the custom property will not be updated.

I hope it describes the issue. :)

**Comment by hilljh82** [comment]
@Ajnasz Thank you for the example. The example illustrates what I assumed you were talking about. 

After looking at your solution and the current implementation, I want to rewrite the approach for observing changes to the attributes. My concern with your solution (which solves the current problem), and the current implementation (my overall approach), is it does not scale if you have many custom properties on a component. As the current implementation stands, making a change to one attribute will trigger all attributes—even the unrelated ones—to "refresh". There is a guard in the `ComputedProperty` class, but we need to do away with this unnecessary check. I have a solution to address this problem. It will also address the issue you are currently experiencing. I would therefore would like to redesign the update logic so it is scalable and close this issue if resolves the problem you are currently experiencing.

**Comment by hilljh82** [comment]
@Ajnasz v1.1.1 has a fix for this issue.

**Pull request closed without merging**
